### ISSUE TITLE
Impersonation modifies parent worker

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#66] opened 2017-02-23 21:58 UTC
Well, that's a terrible title, but...

When you impersonate a worker and change their settings, those settings changes get applied to both the impersonatee and the impersonator.

**Comment by nbeernink** [comment] 2017-02-26 11:53
I understand what you mean by this. Almost filed it myself because I happened to me too on 7.2

**Comment by jstanden** [comment] 2017-03-01 00:17
@Hildy Do you have a specific setting I can reproduce with?  I've tried language, timezone, time format, gender, first name, assist mode, etc.  None of them affect the admin's own settings.

**Comment by jstanden** [comment] 2017-03-01 01:58
It's not reproducible on Mac/Safari, but I can reproduce it with Windows/Chrome.

**Comment by jstanden** [comment] 2017-03-01 02:11
This is because `window.reload()` after the Ajax request is re-submiting the form.

**Comment by jstanden** [comment] 2017-03-01 02:34
Fixed in 7.3.3!

**Closed as completed by jstanden** 2017-03-01 02:34 UTC
Labels: bug
