### ISSUE TITLE
"Send email to recipients" sending anomaly

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#945] opened 2019-06-04 00:52 UTC
So I think I may have found an issue or just an understanding problem.

When trying to send an auto response to a sender, our bots do this based on the destination group using "Send email to recipients".

This works great (it uses the group details and correct HTML template based on the group settings) but we've noticed that some of the messages were not working (i.e no response to the sender). It should be noted this works well as we have multiple brands that will use the same rule and the content is correctly formatted.

![Screenshot 2019-06-04 at 1 48 07 AM](https://user-images.githubusercontent.com/15971590/58843538-da61ab00-866a-11e9-9409-8775f0e90f38.png)

For example. On incoming routing we have jam@*domain.com to move to the Jam group. Works fine. Mails to the exact group address also get the auto response, correctly formatted (using the HTML template set on the group) and from the right group name and address. Emails to any other address mapped on the incoming don't get sent.

Should be noted that if we disable the "Don't save a copy of this message in the conversation history." option, messages always get sent - but that option isn't ideal here (as then other bots run and do post-reply actions to to the ticket).

If we use "Send email", we can set each variable but the HTML template is not picked up from the group as the other option is meaning we'd need to set that manually per email sent thus duplicating the email sending bot by a factor of about 6.

![Screenshot 2019-06-04 at 1 48 14 AM](https://user-images.githubusercontent.com/15971590/58843639-4a703100-866b-11e9-8712-54afed9786ef.png)

From the testing we've done, the bots run and it appears cerb goes to send an email but actually does nothing. No interaction with the mail server and even when the mail server is taken offline, no message in the queue.

I _think_ it might be something to do with the group email address but one would assume that if the mail has been moved to the group the "Send email to recipients" it would send from that group name, email and template. Just as it does when you send a mail manually.

**Comment by jstanden** [comment] 2019-06-06 19:10
Hi @iammattmartin!

I'll see if I'm able to reproduce this with the example above.

**Comment by iammattmartin** [comment] 2019-06-06 19:24
Thanks Jeff,

The ideal outcome would actually be fixing, or making "Send Mail" to obey the HTML template as the group uses like "Send email to receipts" does which then fixes this issue (at least for us) but also makes both options consistent which each other in terms of message formatting (and actually solves a few other uses where that would be better for us).

**Comment by iammattmartin** [comment] 2019-07-11 23:27
This still appears to happen with the latest release, would be good for a solution as lots of emails are not getting auto responders sent in the current form.

**Comment by jstanden** [comment] 2019-07-11 23:41
I can reproduce that 'Send email' doesn't inherit the group/bucket template for 'Send from' when blank.

However, I can't reproduce the issue with mail not sending with either 'Send email' or 'Send email to recipients'.

Is there a consistent set of sender email addresses that don't work? Can you verify their mail transport in Search->Email Addresses? They should have "We send email from this address" enabled, and they must not also be assigned to a worker.

**Comment by iammattmartin** [comment] 2019-07-12 00:03
Noted on the first. Would be nice for that to match the Sent to Recipients formatting.

Ah, ok. This answers the main issue but it but leads to more inconsistency. We only had the group address set to one that we send from. Setting the alternative (incoming) address to that also works.

However, the message is still sent from the group address so should the secondary addresses really need them set to "we send email from this address" because in reality, mail isn't being sent from that address.

**Comment by jstanden** [comment] 2019-07-12 19:37
Hi Matt!

The wording is perhaps confusing, but the flag on the email address is really about whether Cerb controls that mailbox or not. If you also _receive_ to that address then you should set that flag. It helps prevent against mail loops where a bot sends mail to itself.

Cerb can't send mail from an address unless a mail transport is set up for it (determining SMTP server + credentials).

From what you're saying, it seems like the group and its buckets just use one address to reply, and that has a mail transport set up. It's odd you're not seeing any connections to the SMTP server. In the code, the only blocking issue there is the mail transport for the sender address.

I'll try a bit more to see if I can reproduce that.

It should be quick to have 'Send email' use the HTML template from the sender address when in HTML mode w/o a given template. I'll try to get that knocked out this afternoon.

**Comment by iammattmartin** [comment] 2019-07-12 19:55
The use we have is legacy addresses on the incoming routing but any outbound mail from that group goes from the address in use.

When we add the old incoming address, mail does go out via the bot but the from address is still the new/group address. Obviously as I mentioned earlier, the mail isn't going from the old address so it does seem a bit confusing that you need to say you're sending mail from it but yes, it could be the wording.

That itself does pose a problem as we have some incoming mail routing for user@* which would mean we need to add every possible option and that becomes a bit of a task in itself.

"Send Email" may just fix this as long as the view of the message is the same as what would be seen with "Send to recipients".

**Comment by iammattmartin** [comment] 2019-07-13 22:00
I think the issue with "Send Email" is still probably worth checking out. On "new message added to ticket" the bot runs and then initiates the sending of email. Now by this point, the ticket is already created in the group. The group has one email assigned to it, so when that group sends email as from "Send Email" it should be doing so from the group email.

That is the case as long as the incoming email is to that group email. Now I would say the incoming email does not really matter (or shouldn't), as the email is already in that group... and it could have gotten there several ways.

After all, you're asking it to send email from the group and the event is after the incoming message already assigned to the ticket and isn't dependent on it.

**Comment by iammattmartin** [comment] 2020-03-15 03:19
Bit of an o/s one but I tested with "We send email from this address" on the incoming address that is routed to a group but even with that, the message isn't sent [although the message would come from the group address]

Although the logic still shouldn't require that as far as I can see.

**Closed as not planned** 2023-01-21 01:29 UTC
