### ISSUE TITLE
[Docs/Guides] Sending HTML messages from bots (w/ inline images + sigs)

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#520] opened 2017-11-08 19:42 UTC

**Comment by dransome** [comment] 2020-05-05 19:06
Currently taking another look at Cerb, and one of our long standing bug bears remains intact in that we can't put images in signature with ticket placeholders in image link URL. Basically, there's no way to use (actual) HTML in signatures, only markdown which is very limiting when trying to craft a HTML template.

Looks like this guide might address a potential workaround?

**Comment by Hildy** [comment] 2020-05-14 19:18
You should be able to put straight HTML content in the emails and HTML sigs, not just markdown.

With this email:
![image](https://user-images.githubusercontent.com/64052/81975857-80889580-95dc-11ea-9283-074f3abbd8ca.png)

and this sig:
![image](https://user-images.githubusercontent.com/64052/81975914-972eec80-95dc-11ea-8536-73cd6cd0a613.png)

and this template:
![image](https://user-images.githubusercontent.com/64052/81976021-c6ddf480-95dc-11ea-95e9-19f661b81d04.png)

I get this email:
![image](https://user-images.githubusercontent.com/64052/81976175-00166480-95dd-11ea-852c-91c30da234fe.png)

**Comment by dransome** [comment] 2020-05-15 09:18
Interesting - so maybe the issue is that the HTML has to be valid/complete within a particular segment?

I previously tried to open a table in the template, and close it within a signature (due to needing to access placeholders), and it didn't work - the HTML was converted to entities.

Since even the signature only has access to worker placeholders, it still wasn't enough so we've reverted to our old workaround of appending the signature to the message content on the "before message sent by group member" event, and using markdown in there (though I may try convert that markdown to HTML and see if that works out, because at the moment there's no alt text used for the plain text conversion).

We have something like this appended to the message content by the bot to create our "signature":
```
[![Awesome](https://emailimg.domain.com/rating-awesome.png)](https://ratings.domain.com/billing/{{worker_first_name}}.{{worker_last_name}}/{{ticket_mask}}?s=10)
```
That works fine in HTML, but is completely blank on the plain text conversion; I'd expect some sort of reasonable text representation of that such as `Awesome: https://ratings.domain.com/billing/{{worker_first_name}}.{{worker_last_name}}/{{ticket_mask}}?s=10`

Ultimately all of this is less elegant than if the {{ticket_mask}} were available in the signature feature (then we could just specify our own plain text representation directly), but such is Cerb.

Unfortunately there are quite a lot of quirks and tricks needed to get Cerb to behave how we want in terms of message formatting. That's why the addition of extra docs around this would be very welcome: Cerb can do most things, but figuring out the tricks needed to do it is a long slow and frustrating road.

**Closed as not planned** 2023-01-21 01:14 UTC
