### ISSUE TITLE
Move org/address entries in Compose to new choosers

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#99] opened 2017-03-07 18:23 UTC
The Org and To/CC/BCC fields in the Compose dialog should use the new choosers instead of the old autocomplete fields.

**Comment by jstanden** [comment] 2017-08-04 21:05
To/Cc/Bcc allow choosers now.  Org doesn't yet, but should.

**Comment by iammattmartin** [comment] 2017-08-05 21:58
Will this allow static cc: addresses like the to: field or will they only be used for the one time message?

**Comment by jstanden** [comment] 2017-10-06 19:00
At the moment, and by design, Cc/Bcc are always one-off copies for an individual message.  We've had requests in the past for ongoing participants to be assigned to To/Cc/Bcc, but we currently don't make that distinction (per #421)

**Comment by iammattmartin** [comment] 2020-01-16 17:25
As this one is a long time open, has there been any scope to allow cc (and bcc) to be hard set addresses for a ticket? It would solve a long term frustration when sub-contacts on an account message in but only the main contact can be put in to to: due to limitations with brands/changing emails.

**Comment by jstanden** [comment] 2020-01-16 19:29
On the database/schema side, it would just be a new field in the `email<->ticket` intermediary table for participants where we could track `to`/`cc`/`bcc` as types, and use that on replies. Every existing row could default to `to`.

It's a little more complicated in the UI because the types would have to be managed somehow. It's currently simple to explain that only the `To:` list currently changes the participants. For one-offs, you can use 'Reply to only these recipients' to copy a message's headers.

One option that would work in the current version would be to add a 'Record links' (to email addresses) custom field on tickets (or as a ticket fieldset) for these Cc/Bcc participants. Then a 'Before starting a reply' behavior could append those links into the Cc/Bcc field. The only tricky part I'd anticipate there would just be filtering any existing values in those fields to remove dupes.

**Comment by iammattmartin** [comment] 2020-01-17 16:35
I think the use case for us is that the to: is set to the main account contact and the cc: has previously (pre-cerb) been used for if a request is raised by one of the main account contacts sub-contacts. So the ticket still belongs to the overall user and can be seen by them but the sub-account contact gets direct updates too.

As we're replying, there is no direct correlation between sub-account and ticket so the only way we could manage that is setting directly on the ticket, which can't be done due to that not being hard-set.

**Comment by jstanden** [comment] 2020-01-17 20:03
Ticket-based custom fields can be set on a reply, but they wouldn't appear naturally into the To/Cc/Bcc list, like would be helpful for something like this.

I'm not a big fan of all ticket custom fields showing up on the reply form anyway. Perhaps we're in need of a widget based approach to the reply form as well, where elements are customizable, and could be conditional based on aspects of the ticket/worker/group/etc.

I do agree with the intent of this -- keeping the context of a participant as a To/Cc/Bcc -- but allowing that potentially complicates participants. What you're after is almost like another set of recipient fields (derived from the ticket) that combine with the standard To/Cc. Doing that is easy enough, but it also needs to be obvious it's happening from the reply form in the UI.

I feels like it would add UI complexity to allow some To/Cc/Bcc recipients to be permanent per ticket, and others not. Are you envisioning that would just happen when editing the ticket rather than replying, and it would lock those in so they aren't editable on reply?

**Comment by iammattmartin** [comment] 2020-01-17 20:08
On the latter point, pretty much.

Although for us, using the API, we would only ever use what is pre-filled in that field. I can see scope for others to add one-time addresses is the current working of the field but also want other addresses to be sticky.

It kind of needs a field that allows selectors for fixed addresses which can be easily removed but also one-times too. Tricky.

**Closed as not planned** 2023-01-21 01:01 UTC
