### ISSUE TITLE
Chrome inserts text (snippets, sigs) at the first blank line, not the current cursor location

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#226] opened 2017-05-30 19:30 UTC
This is a fairly recent behavior in Chrome (within the last few weeks), and I confirmed that it does *not* do this in Firefox.

**Comment by jstanden** [comment] 2017-05-30 19:45
I can't reproduce this using Chrome 58.0.3029.110 (64-bit) on macOS Sierra 10.12.4 (16E195) with 7.3.13 or 8.0.

I'll try with Windows.

**Comment by jstanden** [comment] 2017-05-30 19:50
I can't repro on Chrome 58 on Windows 8.0, 8.1, or 10.

There must be another part to this.

**Comment by jstanden** [comment] 2017-05-30 23:03
Steps to repro:
1. Click 'Reply' on a ticket
2. Hold `SHIFT` and press `DOWN` several times
3. Press `ENTER` several times
4. `Ctrl+Shift+I` to insert a snippet.

Expected:
The snippet inserts at the cursor.

Actual:
In Chrome 58, the snippet inserts on the first line above the `ENTER` blank lines (string position 0).

**Comment by jstanden** [comment] 2017-05-31 01:14
I reported this upstream to Chrome:

URL: https://jsfiddle.net/781fypo4/6/

Chrome 58.x and 59.x are reporting incorrect text selection ranges and cursor positions if the start text of a range is any number of blank lines from pressing ENTER/RETURN.  This did not occur on versions 50.x through 57.x.

Steps to reproduce:
1. In the attached jsFiddle URL, use the mouse to place the cursor after '8' and press ENTER three times.
2. In the developer console you'll see a text selection range of 18:18, which is correct.
3. Click the 'Insert' button above the textarea.
4. You'll see "{{snippet}}" inserted at the beginning of the range, rather than where the cursor was.  This is reproducible with any number of CRLF/LF.  You'll also see the reported cursor position in the console has moved to the beginning of the sequence of CRLF/LF with no user movement of the cursor.

Expected result:
"{{snippet}" inserts at the cursor at character position #18

Actual result:
"{{snippet}}" inserts at character position #15, after the first non-CRLF character *before* the cursor.

You can run the jsFiddle on any version prior to Chrome 58.0 and get the expected result.  With versions 58.0 and 59.0 you get the incorrect result.

You can also use the CTRL+SHIFT+I shortcut to insert a snippet at the correct position (pos=18). This avoids a blur event on the textarea, which may offer a clue (perhaps a left trim on the selection when re-focusing the textarea, etc).

**Comment by jstanden** [comment] 2017-10-06 18:42
Based on the jsFiddle example above, this appears to be fixed in Chrome 59.0.3071.86+, 60.x, and 61.x.

**Closed as completed by jstanden** 2017-10-06 18:42 UTC
Labels: bug
