### ISSUE TITLE
Replace text in message seems to match once and die

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#475] opened 2017-10-23 03:00 UTC
Using the replace feature to strip out incoming content seems to work but only on the first match.

Our logic and tree is like the very old example at http://wiki.cerbweb.com/File:C560_va_action_replace_regexp.png

<img width="289" alt="screen shot 2017-10-23 at 3 57 48 am" src="https://user-images.githubusercontent.com/15971590/31870525-5df69a06-b7a6-11e7-88bc-67f75b5f65c0.png">

To test this, we've added a rule to strip the from line and the indented content.

<img width="664" alt="screen shot 2017-10-23 at 3 58 28 am" src="https://user-images.githubusercontent.com/15971590/31870555-77ed6098-b7a6-11e7-8e48-0b7880996d47.png">

This only inserts the word header (as expected) but does nothing with the body.

Splitting the parts out to one rule under the other, it only ever matches the first. i.e if we switch the body rule to be first, that matches but then ignores the from/header.

The content:

```
Test Message

On 23 October 2017 at 02:35, Test Group wrote:

> asasdasdasd
>
> --
> Test Group
> Test Company Ltd.
>
> w: https://www.test.net/
> t: 0000 0000 0000 
>
```

This also then means any other rules are skipped completely, when there may be other matched content.

**Comment by jstanden** [comment] 2017-10-23 16:19
Thanks for the report! I'll see if I can repro this today.

**Comment by jstanden** [comment] 2017-10-23 17:29
Fixed in 8.1.6.

**Comment by iammattmartin** [comment] 2017-10-23 18:31
Have just tested this one with the same message as in the original post but it still seems to only match once be it in the same action or sub-actions. (Swapping them matches the second rule so I can be sure the rule is working just the message never seems to go to it).

Actually, have just noted that the bug seems to be "Before message sent from worker" but the event I was testing was "Before new incoming message was accepted". Does the same fix need to be applied there @jstanden?

**Comment by jstanden** [comment] 2017-10-23 18:56
@mattmartincouk Yeah, I'll check the other event too.  Good catch!

**Comment by jstanden** [comment] 2017-10-23 19:14
I can't reproduce this with that event.  The 'body' check above should be using the `m` flag for a multi-line match. Otherwise it's only matching per line by default. I couldn't get the other regexp to match no matter what order it was in.

I used:
`#(^>.*(\n|$)){1,}#m`

You could try an even simpler regexp to just verify it's working at all.  Have two actions change `On` -> `ON` and `Test` -> `TEST`.

**Comment by jstanden** [comment] 2017-10-23 19:15
<img width="907" alt="screen shot 2017-10-23 at 12 14 51 pm" src="https://user-images.githubusercontent.com/63288/31908472-d6795744-b7eb-11e7-8e48-27d7f27fae38.png">

**Comment by iammattmartin** [comment] 2017-10-23 22:49
Thanks for the tips. Wasn't aware you could use the m expression.

**Comment by iammattmartin** [comment] 2017-10-23 23:11
I've tested and whilst when running the simulator as per your example it strips as expected, it still only seems to do this once with a real email.

This is what I have set now.

<img width="662" alt="screen shot 2017-10-24 at 12 08 34 am" src="https://user-images.githubusercontent.com/15971590/31917431-803e06a4-b84f-11e7-8f78-af2f39f2a377.png">

It strips the first match but never gets to the second. Moving the second to be first, strips the indents but not the from line.

Regexppal confirms they are both valid and should.

**Comment by iammattmartin** [comment] 2017-10-23 23:39
Altered to ```#On \d{1,2}\D\w{1,10}\D\d{1,4} at \d{1,2}:\d{1,2},.*wrote:(\n|.*){1,}#m``` which works as it is on one line but matching more than one rule appears to not.

**Comment by iammattmartin** [comment] 2017-10-23 23:44
Tried two rules in line with specific content types but after the first it does not get to the second. Both rules work when they are first so I think the issue remains.

**Comment by jstanden** [comment] 2017-10-23 23:48
k! I'll give it a full test with live email too.

**Comment by iammattmartin** [comment] 2017-10-23 23:48
Thanks. Have tested with Gmail for webmail and Mailmate/Mac Mail and have been able to replicate in all instances.

**Comment by jstanden** [comment] 2017-11-17 19:29
If I create a behavior with multiple replacements (both in the same action and multiple actions):

<img width="628" alt="multple-replace" src="https://user-images.githubusercontent.com/63288/32965063-343042d8-cb8a-11e7-9a41-6b8a5c3a1f51.png">

Then I import a message like:

~~~
To: support@cerb.example
From: customer@cerb.example
Subject: This is a test with multiple rewrites

AAABBBCCCDDD
DDDCCCBBBAAA
~~~

I get the body:

~~~
[[AAA]][BBB][CCC][DDD]
[DDD][CCC][BBB][[AAA]]
~~~

That even includes a test where a subsequent replacement changes the substitution from an earlier message.

There doesn't appear to be an issue with multiple replacements taking place.  Although there may be something else involved.

Can you build a minimal behavior example that reproduces the issue, then export it to JSON and paste it here?  Provide a test raw email message too.

**Comment by jstanden** [comment] 2017-12-01 18:31
@mattmartincouk Hey Matt.  I still can't reproduce this.  Let me know if you have an example you can export that reproduces the issue consistently.

**Comment by iammattmartin** [comment] 2017-12-01 18:32
Sorry, have been a bit caught up here but will try a few more tests in the next few days!

**Comment by iammattmartin** [comment] 2017-12-04 21:31
I've managed to work this out.

We have multiple bots for "Before new incoming message is accepted" and for an earlier one to block replies, when a reply is allowed on a group, we exit to speed the processing up. It appears this impacts the later bot to strip the reply content.

Should that happen as we do it in a few places as without, it slows down some bots quite a lot.

**Comment by jstanden** [comment] 2017-12-04 22:29
Thanks! I'll see if I can reproduce it with that input.  It sounds like maybe the event dictionary passed to later behaviors is inheriting the 'exit' flag on those subsequent behaviors.

What you're doing sounds perfectly reasonable to me.

**Comment by iammattmartin** [comment] 2017-12-04 22:29
If you want both bots... I can attach those so you can do real like for like test.

**Comment by jstanden** [comment] 2017-12-04 22:39
Sure, it can't hurt. :)

**Comment by iammattmartin** [comment] 2017-12-05 03:28
Here is my Block Reply bot: The problem exit is titled *THIS*

```
{
    "behavior": {
        "uid": "behavior_315",
        "title": "Block Replies - Test",
        "is_disabled": false,
        "is_private": false,
        "priority": 10,
        "event": {
            "key": "event.mail.received.app",
            "label": "Before new incoming message is accepted"
        },
        "nodes": [
            {
                "type": "switch",
                "title": "Check Source",
                "status": "live",
                "nodes": [
                    {
                        "type": "outcome",
                        "title": "Email",
                        "status": "live",
                        "params": {
                            "groups": [
                                {
                                    "any": 0,
                                    "conditions": [
                                        {
                                            "condition": "header",
                                            "header": "X-HD-Source",
                                            "oper": "!is",
                                            "value": "API"
                                        }
                                    ]
                                }
                            ]
                        },
                        "nodes": [
                            {
                                "type": "switch",
                                "title": "Is this a reply?",
                                "status": "live",
                                "nodes": [
                                    {
                                        "type": "outcome",
                                        "title": "Yes",
                                        "status": "live",
                                        "params": {
                                            "groups": [
                                                {
                                                    "any": 0,
                                                    "conditions": [
                                                        {
                                                            "condition": "parent_ticket_mask",
                                                            "oper": "!is",
                                                            "value": ""
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        "nodes": [
                                            {
                                                "type": "switch",
                                                "title": "Are email replies allowed?",
                                                "status": "live",
                                                "nodes": [
                                                    {
                                                        "type": "outcome",
                                                        "title": "Yes",
                                                        "status": "live",
                                                        "params": {
                                                            "groups": [
                                                                {
                                                                    "any": 0,
                                                                    "conditions": [
                                                                        {
                                                                            "condition": "parent_ticket_group_custom_101",
                                                                            "bool": "1"
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        "nodes": [
                                                            {
                                                                "type": "action",
                                                                "title": "Die - *THIS*",
                                                                "status": "disabled",
                                                                "params": {
                                                                    "actions": [
                                                                        {
                                                                            "action": "_exit",
                                                                            "mode": ""
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        "type": "outcome",
                                                        "title": "No",
                                                        "status": "live",
                                                        "params": {
                                                            "groups": [
                                                                {
                                                                    "any": 0,
                                                                    "conditions": []
                                                                }
                                                            ]
                                                        },
                                                        "nodes": [
                                                            {
                                                                "type": "switch",
                                                                "title": "Check if deleted",
                                                                "status": "live",
                                                                "nodes": [
                                                                    {
                                                                        "type": "outcome",
                                                                        "title": "Yes",
                                                                        "status": "live",
                                                                        "params": {
                                                                            "groups": [
                                                                                {
                                                                                    "any": 0,
                                                                                    "conditions": [
                                                                                        {
                                                                                            "condition": "parent_ticket_status",
                                                                                            "oper": "is",
                                                                                            "value": "deleted"
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        },
                                                                        "nodes": [
                                                                            {
                                                                                "type": "action",
                                                                                "title": "Die",
                                                                                "status": "live",
                                                                                "params": {
                                                                                    "actions": [
                                                                                        {
                                                                                            "action": "_exit",
                                                                                            "mode": ""
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            }
                                                                        ]
                                                                    },
                                                                    {
                                                                        "type": "outcome",
                                                                        "title": "No",
                                                                        "status": "live",
                                                                        "params": {
                                                                            "groups": [
                                                                                {
                                                                                    "any": 0,
                                                                                    "conditions": []
                                                                                }
                                                                            ]
                                                                        },
                                                                        "nodes": [
                                                                            {
                                                                                "type": "switch",
                                                                                "title": "Check if managed/VIP",
                                                                                "status": "live",
                                                                                "nodes": [
                                                                                    {
                                                                                        "type": "outcome",
                                                                                        "title": "Yes",
                                                                                        "status": "live",
                                                                                        "params": {
                                                                                            "groups": [
                                                                                                {
                                                                                                    "any": 1,
                                                                                                    "conditions": [
                                                                                                        {
                                                                                                            "condition": "parent_ticket_custom_131",
                                                                                                            "bool": "1"
                                                                                                        },
                                                                                                        {
                                                                                                            "condition": "parent_ticket_initial_message_sender_contact_custom_84",
                                                                                                            "oper": "in",
                                                                                                            "values": [
                                                                                                                "VIP"
                                                                                                            ]
                                                                                                        }
                                                                                                    ]
                                                                                                }
                                                                                            ]
                                                                                        },
                                                                                        "nodes": [
                                                                                            {
                                                                                                "type": "action",
                                                                                                "title": "Die",
                                                                                                "status": "live",
                                                                                                "params": {
                                                                                                    "actions": [
                                                                                                        {
                                                                                                            "action": "_exit",
                                                                                                            "mode": ""
                                                                                                        }
                                                                                                    ]
                                                                                                }
                                                                                            }
                                                                                        ]
                                                                                    },
                                                                                    {
                                                                                        "type": "outcome",
                                                                                        "title": "No",
                                                                                        "status": "live",
                                                                                        "params": {
                                                                                            "groups": [
                                                                                                {
                                                                                                    "any": 0,
                                                                                                    "conditions": []
                                                                                                }
                                                                                            ]
                                                                                        },
                                                                                        "nodes": [
                                                                                            {
                                                                                                "type": "switch",
                                                                                                "title": "Check Brand",
                                                                                                "status": "live",
                                                                                                "nodes": [
                                                                                                    {
                                                                                                        "type": "outcome",
                                                                                                        "title": "Brand Name",
                                                                                                        "status": "live",
                                                                                                        "params": {
                                                                                                            "groups": [
                                                                                                                {
                                                                                                                    "any": 0,
                                                                                                                    "conditions": [
                                                                                                                        {
                                                                                                                            "condition": "parent_ticket_custom_26",
                                                                                                                            "oper": "in",
                                                                                                                            "values": [
                                                                                                                                "XILO"
                                                                                                                            ]
                                                                                                                        }
                                                                                                                    ]
                                                                                                                }
                                                                                                            ]
                                                                                                        },
                                                                                                        "nodes": [
                                                                                                            {
                                                                                                                "type": "action",
                                                                                                                "title": "Send Email",
                                                                                                                "status": "live",
                                                                                                                "params": {
                                                                                                                    "actions": [
                                                                                                                        {
                                                                                                                            "action": "_set_custom_var_snippet",
                                                                                                                            "on": "parent_ticket_id",
                                                                                                                            "snippet_id": "74",
                                                                                                                            "var": "name"
                                                                                                                        },
                                                                                                                        {
                                                                                                                            "action": "_set_custom_var_snippet",
                                                                                                                            "on": "parent_ticket_id",
                                                                                                                            "snippet_id": "89",
                                                                                                                            "var": "message"
                                                                                                                        },
                                                                                                                        {
                                                                                                                            "action": "_set_custom_var_snippet",
                                                                                                                            "on": "parent_ticket_id",
                                                                                                                            "snippet_id": "86",
                                                                                                                            "var": "signature"
                                                                                                                        },
                                                                                                                        {
                                                                                                                            "action": "_set_custom_var_snippet",
                                                                                                                            "on": "parent_ticket_id",
                                                                                                                            "snippet_id": "84",
                                                                                                                            "var": "terms"
                                                                                                                        },
                                                                                                                        {
                                                                                                                            "action": "send_email",
                                                                                                                            "from_address_id": "10",
                                                                                                                            "to": "{{sender_address}}",
                                                                                                                            "cc": "",
                                                                                                                            "bcc": "",
                                                                                                                            "subject": "Returned: {{parent_ticket_subject}}",
                                                                                                                            "html_template_id": "2",
                                                                                                                            "format": "parsedown",
                                                                                                                            "content": "{{name}}\r\n\r\n{{message}}\r\n\r\n<p><br></p>\r\n<p>{{signature}}</p>\r\n<p></p>\r\n<p id=\"small\">{{terms}}</p>",
                                                                                                                            "headers": "",
                                                                                                                            "run_in_simulator": "0"
                                                                                                                        },
                                                                                                                        {
                                                                                                                            "action": "reject"
                                                                                                                        }
                                                                                                                    ]
                                                                                                                }
                                                                                                            }
                                                                                                        ]
                                                                                                    }
                                                                                                ]
                                                                                            }
                                                                                        ]
                                                                                    }
                                                                                ]
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        "type": "outcome",
                                        "title": "No",
                                        "status": "live",
                                        "params": {
                                            "groups": [
                                                {
                                                    "any": 0,
                                                    "conditions": []
                                                }
                                            ]
                                        },
                                        "nodes": [
                                            {
                                                "type": "action",
                                                "title": "Die",
                                                "status": "live",
                                                "params": {
                                                    "actions": [
                                                        {
                                                            "action": "_exit",
                                                            "mode": ""
                                                        }
                                                    ]
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "type": "outcome",
                        "title": "Other",
                        "status": "live",
                        "params": {
                            "groups": [
                                {
                                    "any": 0,
                                    "conditions": []
                                }
                            ]
                        },
                        "nodes": [
                            {
                                "type": "action",
                                "title": "Die",
                                "status": "live",
                                "params": {
                                    "actions": [
                                        {
                                            "action": "_exit",
                                            "mode": ""
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    }
}
```

And the text/replace.

```
{
    "behavior": {
        "uid": "behavior_316",
        "title": "Remove Reply Content",
        "is_disabled": false,
        "is_private": false,
        "priority": 20,
        "event": {
            "key": "event.mail.received.app",
            "label": "Before new incoming message is accepted"
        },
        "nodes": [
            {
                "type": "switch",
                "title": "Check Source",
                "status": "live",
                "nodes": [
                    {
                        "type": "outcome",
                        "title": "API",
                        "status": "live",
                        "params": {
                            "groups": [
                                {
                                    "any": 0,
                                    "conditions": [
                                        {
                                            "condition": "header",
                                            "header": "X-HD-Source",
                                            "oper": "is",
                                            "value": "API"
                                        }
                                    ]
                                }
                            ]
                        },
                        "nodes": [
                            {
                                "type": "action",
                                "title": "Die",
                                "status": "live",
                                "params": {
                                    "actions": [
                                        {
                                            "action": "_exit",
                                            "mode": ""
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "type": "outcome",
                        "title": "Email",
                        "status": "live",
                        "params": {
                            "groups": []
                        },
                        "nodes": [
                            {
                                "type": "switch",
                                "title": "Is Reply?",
                                "status": "live",
                                "nodes": [
                                    {
                                        "type": "outcome",
                                        "title": "Yes",
                                        "status": "live",
                                        "params": {
                                            "groups": [
                                                {
                                                    "any": 0,
                                                    "conditions": [
                                                        {
                                                            "condition": "parent_ticket_mask",
                                                            "oper": "!is",
                                                            "value": ""
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        "nodes": [
                                            {
                                                "type": "action",
                                                "title": "On wrote Google",
                                                "status": "live",
                                                "params": {
                                                    "actions": [
                                                        {
                                                            "action": "replace_content",
                                                            "is_regexp": "1",
                                                            "replace": "#On \\d{1,2}\\D\\w{1,10}\\D\\d{1,4} at \\d{1,2}:\\d{1,2},.*wrote:(\\n|.*){1,}#m",
                                                            "with": ""
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                "type": "action",
                                                "title": "On wrote Google - Split From line",
                                                "status": "live",
                                                "params": {
                                                    "actions": [
                                                        {
                                                            "action": "replace_content",
                                                            "is_regexp": "1",
                                                            "replace": "#On \\d{1,2}\\D\\w{1,10}\\D\\d{1,4} at \\d{1,2}:\\d{1,2},.*\\n.*wrote:.(\\n|.*){1,}#m",
                                                            "with": ""
                                                        }
                                                    ]
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
}
```

**Comment by jstanden** [comment] 2020-06-12 01:31
This functionality was just refactored in 9.6. I'm going to leave this open to verify.

**Comment by jstanden** [comment] 2021-04-28 01:48
I never could reproduce this, but the functionality is moving to the `mail.send` automation event in 10.x.

**Closed as completed by jstanden** 2021-04-28 01:48 UTC
Labels: bug, help wanted
