### ISSUE TITLE
[API] Pagination fails when a quick search 'q' string is present

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#441] opened 2017-09-21 14:43 UTC
It's been reported a couple times in the last two days that when using the API, paging the results works *until* you add a 'q' search string.  With that query string, regardless of the page requested, the API returns the first page of results.

**Comment by jstanden** [comment] 2017-09-21 16:15
This is probably due to `addParamsWithQuery()` resetting the paging.  I'll reproduce it and get a fix into 8.1.3.

**Comment by jstanden** [comment] 2017-09-21 16:56
Fixed in 8.1.3

**Closed as completed by jstanden** 2017-09-21 16:56 UTC
Labels: bug
