### ISSUE TITLE
API reports that a ticket doesn't exist when the worker doesn't have access to it

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#383] opened 2017-08-29 20:32 UTC
Instead of telling you that the ticket doesn't exist (when it's in a group your API keys aren't a member of), the error message should inform you that you don't have access to that ticket.

**Comment by jstanden** [comment] 2017-09-21 19:10
This happens because the `GET` action uses `search` behind the scenes, and the group memberships are one of the filters. We'd need to switch this to `::get()` and reproduce the dictionary output of search to give a better error message.

**Comment by jstanden** [comment] 2021-04-28 01:36
This hasn't come up again. Closing for now.

**Closed as completed by jstanden** 2021-04-28 01:36 UTC
