### ISSUE TITLE
Add auto-hide for blockquotes displayed in HTML emails

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#551] opened 2017-12-05 17:35 UTC
We auto-hide multiple (3+, IIRC) lines of quoted text in plain-text display of messages, so can we also do something similar for blockquoted sections of html displayed messages?

**Comment by jstanden** [comment] 2017-12-06 19:21
Dupe of #261

**Closed as completed by jstanden** 2017-12-06 19:21 UTC
