### ISSUE TITLE
Widget click-through

### ISSUE THREAD

**Issue by johnryanlee** [jstanden/cerb#527] opened 2017-11-10 07:35 UTC
Feature request:
Ability to click on a widget data point which will bring up the worklist showing the information that makes up the data.

EG:
- line/bar chart showing data from a ticket worklist based on priorities (custom field - single line string) for last 7 days
- I'd like to be able to click on the results for P1's on Tuesday to see the list of tickets

**Comment by jstanden** [comment] 2017-11-10 16:58
Hi Ryan! This is a dupe of #87 (though this is more informative). I rescheduled that for 8.3 so we can give it another look. With all the new platform features this year it should be really simple to do now.

**Closed as completed by jstanden** 2017-11-10 16:58 UTC
